# **1. 파이토치**
PyTorch는 파이썬 기반의 오픈소스 딥러닝 프레임워크로, 파이썬 코드로 AI 모델을 직관적으로 만들고 학습할 수 있도록 도와주는 도구입니다.  
특히 동적 계산 그래프 방식을 사용하기 때문에 코드 실행 시점에 실시간으로 계산 흐름이 결정되어 디버깅과 수정이 쉽고, GPU 가속과 자동 미분 기능을 통해 대규모 모델도 빠르게 학습할 수 있습니다.

### ※ 동적 계산 그래프 방식

딥러닝 모델이 학습 및 예측을 수행할 때 계산 그래프를 실행 시점(runtime)에 실시간으로 생성 및 수정하는 방식입니다.  
이 방식은 조건문, 반복문 등 복잡한 논리 구조를 유연하게 처리할 수 있으며, 주로 PyTorch와 같은 프레임워크에서 사용됩니다.  
계산 그래프는 입력 데이터를 바탕으로 연산을 수행하면서 그래프를 생성하고, 역전파를 통해 미분을 계산하며, 최종적으로 가중치를 업데이트하는 과정을 거칩니다.  
이러한 특성 덕분에 디버깅이 용이하고 연구 및 개발 속도가 빠르며 직관적인 코드 작성이 가능합니다.

In [1]:
import torch

In [2]:
if torch.cuda.is_available():
    DEVICE = torch.device('cuda')
elif torch.backends.mps.is_available():
    DEVICE = torch.device('mps')
else:
    DEVICE = torch.device('cpu')

print(DEVICE)

cpu


### 1. 스칼라

스칼라(Scalar)는 단 하나의 숫자(정수, 실수 등)만을 담는 자료형을 말합니다.  
파이토치(PyTorch)에서 스칼라는 0차원 텐서(0-dimensional Tensor)로 표현합니다.  
즉, 텐서의 차원(Shape)이 전혀 없는 상태를 의미합니다.

In [3]:
var1 = torch.tensor(5)
print(var1)
print(var1.shape)

var2 = torch.tensor([10])
print(var2.shape)
var2 = torch.tensor([10, 20, 30])
print(var2.shape)

var3 = torch.tensor(3) 
result = var1 + var3 
print(result)

tensor(5)
torch.Size([])
torch.Size([1])
torch.Size([3])
tensor(8)


In [4]:
ar1 = torch.tensor(5)
print(var1)
print(var1.shape)

var2 = torch.tensor([10])
print(var2.shape)
var2 = torch.tensor([10, 20, 30])
print(var2.shape)

var3 = torch.tensor(3)
result = var1 + var3
print(result)
print(result.item())

tensor(5)
torch.Size([])
torch.Size([1])
torch.Size([3])
tensor(8)
8


2. 벡터(Vector)

벡터(Vector)는 하나 이상의 원소가 일렬로 나열된 1차원 텐서(1D Tensor)를 의미합니다. 파이토치(PyTorch)에서 벡터는 일반적으로 torch.tensor([...]) 형태로 만들며, 이때 텐서의 shape(차원)가 (n,) 형태입니다. 즉, 원소가 n개 들어 있으면 1차원 벡터가 됩니다.

In [5]:
var1 = torch.tensor([1.0, 2.0, 3.0])
print(var1)
print(var1.shape) # torch.Size([3]) -> 1차원 텐서

var2 = var1 + 10
print(var2)
var3 = var1 * 2
print(var3)

var4 = torch.tensor([4.0, 5.0, 6.0])
result = var1 + var4
print(result)

# 사이즈가 달라서 오류남 
# var5 = torch.tensor([4.0, 5.0])
# result = var1 + var5
# print(result)

tensor([1., 2., 3.])
torch.Size([3])
tensor([11., 12., 13.])
tensor([2., 4., 6.])
tensor([5., 7., 9.])


### 3. 행렬

행렬(Matrix)은 2차원 형태의 텐서로, 파이토치(PyTorch)에서는 shape가 (m, n)처럼 2개의 차원을 가진 텐서를 의미합니다. 
<br>예를 들어, torch.tensor([[1, 2], [3, 4]])는 2행×2열 형태의 행렬입니다. 행렬 연산에서는 행렬 곱셈, 원소별 연산, 전치(Transpose) 등이 자주 활용되며, 
<br>파이토치는 torch.mm 또는 @ 연산자를 통해 행렬 곱셈을 수행할 수 있습니다.

In [6]:
var1 = torch.tensor([[1, 2], [3, 4]])
var2 = torch.tensor([[5, 6], [7, 8]])

print(var1)
print(var1.shape) # torch.Size([2, 2]) -> 2차원 텐서

result1 = var1 + var2
print(result1)
result2 = var1 * var2
print(result2)

result3 = torch.mm(var1, var2)
print(result3)
result4 = var1 @ var2
print(result4)

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])
tensor([[ 6,  8],
        [10, 12]])
tensor([[ 5, 12],
        [21, 32]])
tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])


### 4. 다차원 텐서

파이토치(PyTorch)에서 다차원 텐서란, 여러 축(차원)을 가지는 텐서를 의미합니다. 
<br>예를 들어, 0차원 텐서는 “스칼라(Scalar)”, 1차원 텐서는 “벡터(Vector)”, 2차원 텐서는 “행렬(Matrix)”, 
<br>그 이상의 3차원, 4차원 텐서 등을 통틀어 “다차원 텐서(Multi-dimensional Tensor)”라고 부릅니다. 
<br>다차원 텐서는 이미지, 음성, 동영상, 시계열 데이터를 비롯하여 여러 축을 필요로 하는 다양한 형태의 데이터를 표현할 때 쓰입니다.

![다차원 텐서](./images/다차원_텐서.png)